### ISSUE TITLE
3029 - 경고

### ISSUE THREAD

**Issue by nooose** [nooose/algorithm#1]
[경고](https://www.acmicpc.net/problem/3029)

풀고 코멘트에 풀이한 링크 달아 놓기

**Comment by nooose** [comment]
https://github.com/nooose/algorithm/blob/bc3d7a8ca3a1c11d9b5a41dc95763be831819245/baekjoon/solution/src/string/_3029/Main.java

**Comment by nonoro** [comment]
https://github.com/nonoro/testrepository/commit/b834ba09bbfeabe0382074a35142bf3500743fab
