### ISSUE TITLE
완전 탐색

### ISSUE THREAD

**Issue by nooose** [nooose/algorithm#6]
- [x] 3	[22864](https://www.acmicpc.net/problem/22864)	[피로도](https://www.acmicpc.net/problem/22864)		

- [x] 2	[2798](https://www.acmicpc.net/problem/2798)	[블랙잭](https://www.acmicpc.net/problem/2798)	
- [x] 2	[2231](https://www.acmicpc.net/problem/2231)	[분해합](https://www.acmicpc.net/problem/2231)	
- [x] 2	[19532](https://www.acmicpc.net/problem/19532)	[수학은 비대면강의입니다](https://www.acmicpc.net/problem/19532)		
- [x] 2	[18312](https://www.acmicpc.net/problem/18312)	[시각](https://www.acmicpc.net/problem/18312)	
- [x] 1	[15721](https://www.acmicpc.net/problem/15721)	[번데기](https://www.acmicpc.net/problem/15721)

**Comment by nooose** [comment]
- [ ] [피로도](https://www.acmicpc.net/problem/22864)

**Comment by nonoro** [comment]
피로도
https://github.com/nonoro/testrepository/blob/main/src/_22864/Main.java

**Comment by nonoro** [comment]
블랙잭
https://github.com/nonoro/testrepository/blob/main/src/_2798/Main.java

**Comment by nonoro** [comment]
분해합
https://github.com/nonoro/testrepository/blob/main/src/_2231/Main.java

**Comment by nonoro** [comment]
수학은 비대면 강의입니다
https://github.com/nonoro/testrepository/blob/main/src/_19532/Main.java

**Comment by nonoro** [comment]
시각
https://github.com/nonoro/testrepository/blob/main/src/_18312/Main.java

**Comment by nonoro** [comment]
번데기
https://github.com/nonoro/testrepository/blob/main/src/_15721/Main.java
캬캬캬캬캬캬
