### ISSUE TITLE
구현

### ISSUE THREAD

**Issue by nooose** [nooose/algorithm#7]
- [x] 브론즈4 [2753](https://www.acmicpc.net/problem/2753)	[윤년](https://www.acmicpc.net/problem/2753)	

- [x] 브론즈3 [1212](https://www.acmicpc.net/problem/1212)	[8진수 2진수](https://www.acmicpc.net/problem/1212)

- [x] 브론즈3 [20053](https://www.acmicpc.net/problem/20053)	[최소, 최대 2](https://www.acmicpc.net/problem/20053)		
- [x] 브론즈2 [5597](https://www.acmicpc.net/problem/5597)	[과제 안 내신 분..?](https://www.acmicpc.net/problem/5597)		

- [x] 브론즈2 [21918](https://www.acmicpc.net/problem/21918)	[전구](https://www.acmicpc.net/problem/21918)		

- [x] 브론즈1 [20546](https://www.acmicpc.net/problem/20546)	[🐜 기적의 매매법 🐜](https://www.acmicpc.net/problem/20546)

**Comment by nooose** [comment]
- [ ] [윤년](https://www.acmicpc.net/problem/2753)
https://github.com/nooose/algorithm/blob/master/baekjoon/solution/src/impl/_2753/Main.java

- [ ] [8진수 2진수](https://www.acmicpc.net/problem/1212)
https://github.com/nooose/algorithm/blob/master/baekjoon/solution/src/impl/_1212/Main.java

**Comment by nonoro** [comment]
윤년
https://github.com/nonoro/testrepository/blob/main/src/_2753/Main.java

**Comment by nonoro** [comment]
8진수 2진수
https://github.com/nonoro/testrepository/blob/main/src/_1212/Main.java

**Comment by nonoro** [comment]
최소, 최대 2
https://github.com/nonoro/testrepository/blob/main/src/_20053/Main.java

**Comment by nonoro** [comment]
과제 안 내신 분..?
https://github.com/nonoro/testrepository/blob/main/src/_5597/Main.java

**Comment by nonoro** [comment]
전구
https://github.com/nonoro/testrepository/blob/main/src/_21918/Main.java

**Comment by nonoro** [comment]
기적의 매매법
https://github.com/nonoro/testrepository/blob/main/src/_20546/Main.java

야 이거 이상해
